# lang.py

STRINGS = {
    "pt-br": {
        "header_titulo": "⚽ FM Analytics 26",
        "header_caption": "Análise profissional para Football Manager",
        "tab_cadastro": "📝 Cadastrar Partida",
        "tab_dashboard": "📊 Dashboard",
        "tab_historico": "📋 Histórico",
        "tab_ia": "🧠 Assistente IA",
        "cadastro_titulo": "📝 Cadastro da Partida",
        "lbl_seu_time": "Seu time",
        "lbl_adversario": "Time adversário",
        "lbl_local": "Local do jogo",
        "lbl_resultado": "Resultado",
        "lbl_temporada": "Temporada (ex: 2025/26)",
        "lbl_rodada": "Rodada",
        "lbl_competicao": "Competição",
        "lbl_data": "Data da partida",
        "lbl_gols": "Gols",
        "lbl_posse": "Posse de bola (%)",
        "lbl_remates": "Remates",
        "lbl_remates_baliza": "Remates a baliza",
        "lbl_xg": "xG",
        "lbl_oportunidades": "Oportunidades flagrantes",
        "lbl_cantos": "Cantos",
        "lbl_passes_totais": "Passes totais",
        "lbl_passes_certos": "Passes certos",
        "lbl_cruzamentos_totais": "Cruzamentos totais",
        "lbl_cruzamentos_certos": "Cruzamentos certos",
        "lbl_seu_time_stats": "📊 Seu Time",
        "lbl_adv_stats": "📉 Adversário",
        "btn_salvar": "💾 Salvar partida",
        "msg_sucesso": "✅ Partida salva com sucesso!",
        "msg_salvando": "Salvando partida...",
        "limite_dica": "💡 Dica: Libere espaço deletando partidas antigas",
        "limite_info": "Você tem **{atual}/{max}** partidas cadastradas. Delete algumas na aba '📋 Histórico' para liberar espaço.",
        "dashboard_titulo": "📊 Dashboard Geral",
        "filtros_titulo": "🔍 Filtros",
        "lbl_filtro_temporada": "Temporada",
        "lbl_filtro_competicao": "Competição",
        "filtro_todas": "Todas",
        "nenhuma_partida": "🎯 Nenhuma partida cadastrada ainda. Comece adicionando sua primeira partida!",
        "nenhum_filtro": "⚠️ Nenhuma partida encontrada com os filtros selecionados.",
        "resultados_titulo": "🏆 Resultados",
        "total_partidas": "🎯 Partidas",
        "vitorias": "✅ Vitórias",
        "empates": "🤝 Empates",
        "derrotas": "❌ Derrotas",
        "metrica_aproveitamento": "📊 Aproveitamento Geral",
        "dist_resultados": "Distribuição de Resultados",
        "casa_fora_titulo": "🏠 Desempenho: Casa x Fora",
        "em_casa": "🏠 Em Casa",
        "fora": "✈️ Fora",
        "aproveitamento": "Aproveitamento",
        "medias_titulo": "⚡ Médias",
        "gols_jogo": "Gols/jogo",
        "xg_jogo": "xG/jogo",
        "remates_jogo": "Remates/jogo",
        "remates_alvo_jogo": "Remates alvo/jogo",
        "opor_flagrantes_jogo": "Oportunidades flagrantes/jogo",
        "posse_media": "Posse média",
        "acerto_passes": "Acerto de passes",
        "remates_alvo_perc": "Remates no alvo",
        "padrao_europeu": "🌍 Comparação com Padrão Europeu",
        "xg_por_jogo": "xG por jogo",
        "gols_por_jogo": "Gols por jogo",
        "remates_por_jogo": "Remates por jogo",
        "remates_alvo_label": "Remates no alvo",
        "posse_media_label": "Posse média (%)",
        "passes_certos_label": "Passes certos",
        "aproveitamento_label": "Aproveitamento (%)",
        "referencia": "Referência",
        "ultimos_5": "🔥 Últimos 5 Jogos (Seu time x Adversários)",
        "ultimos_5_casa_fora": "🔥 Últimos 5 Jogos (Casa x Fora)",
        "ultimos_5_casa": "🏠 Últimos 5 em Casa",
        "ultimos_5_fora": "✈️ Últimos 5 Fora",
        "nenhum_jogo_casa": "Nenhum jogo em casa.",
        "nenhum_jogo_fora": "Nenhum jogo fora.",
        "xg_medio": "xG médio",
        "cruzamentos_totais_jogo": "Cruzamentos totais/jogo",
        "cruzamentos_certos_jogo": "Cruzamentos certos/jogo",
        "cantos_jogo": "Cantos/jogo",
        "aprov_passes": "Aproveitamento de passes",
        "ultimos_5_casa_label": "Últimos 5 Casa",
        "ultimos_5_fora_label": "Últimos 5 Fora",
        "grafico_resultados": "Gráfico de Resultados",
        "resultados_casa_fora": "Resultados: Casa vs Fora",
        "historico_titulo": "📋 Histórico Completo de Partidas",
        "nenhuma_partida_hist": "Nenhuma partida cadastrada.",
        "gerenciar_titulo": "🗑️ Gerenciar Partidas",
        "selecionar_deletar": "Selecione uma partida para deletar",
        "btn_deletar": "🗑️ Deletar partida selecionada",
        "deletar_sucesso": "✅ Partida deletada com sucesso!",
        "deletar_erro": "❌ Erro ao deletar partida.",
        "ia_titulo": "🧠 Assistente IA — Performance Analyst",
        "ia_descricao": "Análise tática baseada nos dados das suas partidas cadastradas.",
        "ia_sem_partidas": "⚠️ Nenhuma partida cadastrada. Adicione partidas para ativar o Assistente IA.",
        "ia_minimo": "📊 Cadastre pelo menos **3 partidas** para uma análise mais confiável. Você tem **{n}** partida(s).",
        "ia_selecionar": "🔍 Escopo da análise",
        "ia_escopo_todas": "Todas as partidas",
        "ia_escopo_5": "Últimas 5 partidas",
        "ia_escopo_10": "Últimas 10 partidas",
        "ia_analisar": "🪄 Gerar Relatório de Performance",
        "ia_gerando": "Analisando dados táticos...",
        "ia_veredito": "📋 Veredito do Assistente",
        "ia_partidas_usadas": "📌 Análise baseada em **{n}** partida(s)",
        "ia_erro": "❌ Erro ao gerar análise. Tente novamente.",
        "gols_vs_xg": "Gols vs xG ao longo do tempo",
        "login_aviso": "🔒 Faça login para acessar",
        "btn_ir_login": "🔑 Ir para Login",
        "erro_usuario": "Erro ao carregar usuário",
        "resultado_info": "{emoji} Resultado: **{resultado}** ({gols_u} x {gols_a})",
        "footer_email": "📧 E-Mail para contato: onzevirtual1895@gmail.com",
        "footer_seguro": "🔒 Seus dados estão seguros",
        "footer_canal": "Canal Onze Virtual FC",
        "footer_versao": "V 1.12",
        "lbl_idioma": "🌐 Idioma",
        # --- Importação HTML BepInEx ---
        "importar_titulo": "⚽ Importar Estatísticas de Jogadores",
        "importar_descricao": "Carregue o HTML exportado pelo mod BepInEx após a partida para preencher automaticamente as estatísticas individuais.",
        "importar_selecionar_partida": "Selecione a partida para vincular as estatísticas",
        "importar_upload_label": "📂 Carregar arquivo HTML do BepInEx",
        "importar_preview_titulo": "👁️ Pré-visualização — {n} jogador(es) encontrado(s)",
        "importar_confirmar": "✅ Confirmar e Salvar Estatísticas",
        "importar_sucesso": "✅ Estatísticas de {n} jogadores importadas com sucesso!",
        "importar_erro_parse": "❌ Erro ao ler o HTML. Certifique-se de que o arquivo é um export válido do BepInEx.",
        "importar_erro_salvar": "❌ Erro ao salvar no banco. Tente novamente.",
        "importar_sem_jogadores": "⚠️ Nenhum jogador com minutos jogados encontrado no arquivo.",
        "importar_sem_partidas": "⚠️ Nenhuma partida cadastrada. Cadastre uma partida antes de importar.",
        "importar_tab_principal": "📊 Principal",
        "importar_tab_passe": "🎯 Passe",
        "importar_tab_ofensivo": "⚔️ Ofensivo",
        "importar_tab_defensivo": "🛡️ Defensivo",
        "importar_tab_gr": "🧤 Guarda-Redes",
        "importar_tab_bolas_paradas": "⚽ Bolas Paradas",
        "importar_reimportar_aviso": "⚠️ Esta partida já possui estatísticas importadas. Confirmar substituirá os dados anteriores.",
        "ver_stats_jogadores": "👥 Ver Estatísticas dos Jogadores",
        "sem_stats_jogadores": "Nenhuma estatística de jogadores importada para esta partida.",
    },
    "en": {
        "header_titulo": "⚽ FM Analytics 26",
        "header_caption": "Professional Analysis for Football Manager",
        "tab_cadastro": "📝 Register Match",
        "tab_dashboard": "📊 Dashboard",
        "tab_historico": "📋 History",
        "tab_ia": "🧠 AI Assistant",
        "cadastro_titulo": "📝 Match Registration",
        "lbl_seu_time": "Your Team",
        "lbl_adversario": "Opponent",
        "lbl_local": "Venue",
        "lbl_resultado": "Result",
        "lbl_temporada": "Season (e.g.: 2025/26)",
        "lbl_rodada": "Round",
        "lbl_competicao": "Competition",
        "lbl_data": "Match date",
        "lbl_gols": "Goals",
        "lbl_posse": "Possession (%)",
        "lbl_remates": "Shots",
        "lbl_remates_baliza": "Shots on target",
        "lbl_xg": "xG",
        "lbl_oportunidades": "Clear-cut chances",
        "lbl_cantos": "Corners",
        "lbl_passes_totais": "Total passes",
        "lbl_passes_certos": "Accurate passes",
        "lbl_cruzamentos_totais": "Total crosses",
        "lbl_cruzamentos_certos": "Accurate crosses",
        "lbl_seu_time_stats": "📊 Your Team",
        "lbl_adv_stats": "📉 Opponent",
        "btn_salvar": "💾 Save Match",
        "msg_sucesso": "✅ Match saved successfully!",
        "msg_salvando": "Saving match...",
        "limite_dica": "💡 Tip: Free up space by deleting old matches",
        "limite_info": "You have **{atual}/{max}** matches registered. Delete some in the '📋 History' tab to free up space.",
        "dashboard_titulo": "📊 General Dashboard",
        "filtros_titulo": "🔍 Filters",
        "lbl_filtro_temporada": "Season",
        "lbl_filtro_competicao": "Competition",
        "filtro_todas": "All",
        "nenhuma_partida": "🎯 No matches registered yet. Start by adding your first match!",
        "nenhum_filtro": "⚠️ No matches found with the selected filters.",
        "resultados_titulo": "🏆 Results",
        "total_partidas": "🎯 Matches",
        "vitorias": "✅ Wins",
        "empates": "🤝 Draws",
        "derrotas": "❌ Losses",
        "metrica_aproveitamento": "📊 Overall Win Rate",
        "dist_resultados": "Results Distribution",
        "casa_fora_titulo": "🏠 Performance: Home vs Away",
        "em_casa": "🏠 At Home",
        "fora": "✈️ Away",
        "aproveitamento": "Win Rate",
        "medias_titulo": "⚡ Averages",
        "gols_jogo": "Goals/game",
        "xg_jogo": "xG/game",
        "remates_jogo": "Shots/game",
        "remates_alvo_jogo": "Shots on target/game",
        "opor_flagrantes_jogo": "Clear-cut chances/game",
        "posse_media": "Avg possession",
        "acerto_passes": "Pass accuracy",
        "remates_alvo_perc": "Shots on target",
        "padrao_europeu": "🌍 Comparison with European Standards",
        "xg_por_jogo": "xG per game",
        "gols_por_jogo": "Goals per game",
        "remates_por_jogo": "Shots per game",
        "remates_alvo_label": "Shots on target",
        "posse_media_label": "Avg possession (%)",
        "passes_certos_label": "Accurate passes",
        "aproveitamento_label": "Win Rate (%)",
        "referencia": "Benchmark",
        "ultimos_5": "🔥 Last 5 Games (Your Team vs Opponents)",
        "ultimos_5_casa_fora": "🔥 Last 5 Games (Home vs Away)",
        "ultimos_5_casa": "🏠 Last 5 at Home",
        "ultimos_5_fora": "✈️ Last 5 Away",
        "nenhum_jogo_casa": "No home games.",
        "nenhum_jogo_fora": "No away games.",
        "xg_medio": "Avg xG",
        "cruzamentos_totais_jogo": "Total crosses/game",
        "cruzamentos_certos_jogo": "Accurate crosses/game",
        "cantos_jogo": "Corners/game",
        "aprov_passes": "Pass accuracy",
        "ultimos_5_casa_label": "Last 5 Home",
        "ultimos_5_fora_label": "Last 5 Away",
        "grafico_resultados": "Results Chart",
        "resultados_casa_fora": "Results: Home vs Away",
        "historico_titulo": "📋 Full Match History",
        "nenhuma_partida_hist": "No matches registered.",
        "gerenciar_titulo": "🗑️ Manage Matches",
        "selecionar_deletar": "Select a match to delete",
        "btn_deletar": "🗑️ Delete selected match",
        "deletar_sucesso": "✅ Match deleted successfully!",
        "deletar_erro": "❌ Error deleting match.",
        "ia_titulo": "🧠 AI Assistant — Performance Analyst",
        "ia_descricao": "Tactical analysis based on your registered match data.",
        "ia_sem_partidas": "⚠️ No matches registered. Add matches to activate the AI Assistant.",
        "ia_minimo": "📊 Register at least **3 matches** for a more reliable analysis. You have **{n}** match(es).",
        "ia_selecionar": "🔍 Analysis scope",
        "ia_escopo_todas": "All matches",
        "ia_escopo_5": "Last 5 matches",
        "ia_escopo_10": "Last 10 matches",
        "ia_analisar": "🪄 Generate Performance Report",
        "ia_gerando": "Analysing tactical data...",
        "ia_veredito": "📋 Assistant's Verdict",
        "ia_partidas_usadas": "📌 Analysis based on **{n}** match(es)",
        "ia_erro": "❌ Error generating analysis. Please try again.",
        "gols_vs_xg": "Goals vs xG Over Time",
        "login_aviso": "🔒 Please log in to access",
        "btn_ir_login": "🔑 Go to Login",
        "erro_usuario": "Error loading user",
        "resultado_info": "{emoji} Result: **{resultado}** ({gols_u} x {gols_a})",
        "footer_email": "📧 Contact e-mail: onzevirtual1895@gmail.com",
        "footer_seguro": "🔒 Your data is safe",
        "footer_canal": "Onze Virtual FC Channel",
        "footer_versao": "V 1.12",
        "lbl_idioma": "🌐 Language",
        # --- BepInEx HTML Import ---
        "importar_titulo": "⚽ Import Player Statistics",
        "importar_descricao": "Upload the HTML file exported by the BepInEx mod after the match to automatically fill in individual player statistics.",
        "importar_selecionar_partida": "Select the match to link the statistics",
        "importar_upload_label": "📂 Upload BepInEx HTML file",
        "importar_preview_titulo": "👁️ Preview — {n} player(s) found",
        "importar_confirmar": "✅ Confirm and Save Statistics",
        "importar_sucesso": "✅ Statistics for {n} players imported successfully!",
        "importar_erro_parse": "❌ Error reading HTML. Make sure the file is a valid BepInEx export.",
        "importar_erro_salvar": "❌ Error saving to database. Please try again.",
        "importar_sem_jogadores": "⚠️ No players with minutes played found in the file.",
        "importar_sem_partidas": "⚠️ No matches registered. Add a match before importing.",
        "importar_tab_principal": "📊 Main",
        "importar_tab_passe": "🎯 Passing",
        "importar_tab_ofensivo": "⚔️ Offensive",
        "importar_tab_defensivo": "🛡️ Defensive",
        "importar_tab_gr": "🧤 Goalkeeper",
        "importar_tab_bolas_paradas": "⚽ Set Pieces",
        "importar_reimportar_aviso": "⚠️ This match already has imported statistics. Confirming will replace the previous data.",
        "ver_stats_jogadores": "👥 View Player Statistics",
        "sem_stats_jogadores": "No player statistics imported for this match.",
    },
    "es": {
        "header_titulo": "⚽ FM Analytics 26",
        "header_caption": "Análisis profesional para Football Manager",
        "tab_cadastro": "📝 Registrar Partido",
        "tab_dashboard": "📊 Panel",
        "tab_historico": "📋 Historial",
        "tab_ia": "🧠 Asistente IA",
        "cadastro_titulo": "📝 Registro del Partido",
        "lbl_seu_time": "Tu Equipo",
        "lbl_adversario": "Rival",
        "lbl_local": "Lugar",
        "lbl_resultado": "Resultado",
        "lbl_temporada": "Temporada (ej: 2025/26)",
        "lbl_rodada": "Jornada",
        "lbl_competicao": "Competición",
        "lbl_data": "Fecha del partido",
        "lbl_gols": "Goles",
        "lbl_posse": "Posesión (%)",
        "lbl_remates": "Remates",
        "lbl_remates_baliza": "Remates a portería",
        "lbl_xg": "xG",
        "lbl_oportunidades": "Ocasiones claras",
        "lbl_cantos": "Córneres",
        "lbl_passes_totais": "Pases totales",
        "lbl_passes_certos": "Pases acertados",
        "lbl_cruzamentos_totais": "Centros totales",
        "lbl_cruzamentos_certos": "Centros acertados",
        "lbl_seu_time_stats": "📊 Tu Equipo",
        "lbl_adv_stats": "📉 Rival",
        "btn_salvar": "💾 Guardar Partido",
        "msg_sucesso": "✅ ¡Partido guardado con éxito!",
        "msg_salvando": "Guardando partido...",
        "limite_dica": "💡 Consejo: Libera espacio eliminando partidos antiguos",
        "limite_info": "Tienes **{atual}/{max}** partidos registrados. Elimina algunos en la pestaña '📋 Historial' para liberar espacio.",
        "dashboard_titulo": "📊 Panel General",
        "filtros_titulo": "🔍 Filtros",
        "lbl_filtro_temporada": "Temporada",
        "lbl_filtro_competicao": "Competición",
        "filtro_todas": "Todas",
        "nenhuma_partida": "🎯 Ningún partido registrado. ¡Empieza añadiendo tu primer partido!",
        "nenhum_filtro": "⚠️ No se encontraron partidos con los filtros seleccionados.",
        "resultados_titulo": "🏆 Resultados",
        "total_partidas": "🎯 Partidos",
        "vitorias": "✅ Victorias",
        "empates": "🤝 Empates",
        "derrotas": "❌ Derrotas",
        "metrica_aproveitamento": "📊 Rendimiento General",
        "dist_resultados": "Distribución de Resultados",
        "casa_fora_titulo": "🏠 Rendimiento: Local vs Visitante",
        "em_casa": "🏠 En Casa",
        "fora": "✈️ Fuera",
        "aproveitamento": "Rendimiento",
        "medias_titulo": "⚡ Promedios",
        "gols_jogo": "Goles/partido",
        "xg_jogo": "xG/partido",
        "remates_jogo": "Remates/partido",
        "remates_alvo_jogo": "Remates a portería/partido",
        "opor_flagrantes_jogo": "Ocasiones claras/partido",
        "posse_media": "Posesión media",
        "acerto_passes": "Precisión de pases",
        "remates_alvo_perc": "Remates a portería",
        "padrao_europeu": "🌍 Comparación con Estándares Europeos",
        "xg_por_jogo": "xG por partido",
        "gols_por_jogo": "Goles por partido",
        "remates_por_jogo": "Remates por partido",
        "remates_alvo_label": "Remates a portería",
        "posse_media_label": "Posesión media (%)",
        "passes_certos_label": "Pases acertados",
        "aproveitamento_label": "Rendimiento (%)",
        "referencia": "Referencia",
        "ultimos_5": "🔥 Últimos 5 Partidos (Tu equipo vs Rivales)",
        "ultimos_5_casa_fora": "🔥 Últimos 5 Partidos (Local vs Visitante)",
        "ultimos_5_casa": "🏠 Últimos 5 en Casa",
        "ultimos_5_fora": "✈️ Últimos 5 Fuera",
        "nenhum_jogo_casa": "Ningún partido en casa.",
        "nenhum_jogo_fora": "Ningún partido fuera.",
        "xg_medio": "xG medio",
        "cruzamentos_totais_jogo": "Centros totales/partido",
        "cruzamentos_certos_jogo": "Centros acertados/partido",
        "cantos_jogo": "Córneres/partido",
        "aprov_passes": "Precisión de pases",
        "ultimos_5_casa_label": "Últimos 5 Casa",
        "ultimos_5_fora_label": "Últimos 5 Fuera",
        "grafico_resultados": "Gráfico de Resultados",
        "resultados_casa_fora": "Resultados: Local vs Visitante",
        "historico_titulo": "📋 Historial Completo de Partidos",
        "nenhuma_partida_hist": "Ningún partido registrado.",
        "gerenciar_titulo": "🗑️ Gestionar Partidos",
        "selecionar_deletar": "Selecciona un partido para eliminar",
        "btn_deletar": "🗑️ Eliminar partido seleccionado",
        "deletar_sucesso": "✅ ¡Partido eliminado con éxito!",
        "deletar_erro": "❌ Error al eliminar el partido.",
        "ia_titulo": "🧠 Asistente IA — Analista de Rendimiento",
        "ia_descricao": "Análisis táctico basado en los datos de tus partidos registrados.",
        "ia_sem_partidas": "⚠️ Ningún partido registrado. Añade partidos para activar el Asistente IA.",
        "ia_minimo": "📊 Registra al menos **3 partidos** para un análisis más fiable. Tienes **{n}** partido(s).",
        "ia_selecionar": "🔍 Alcance del análisis",
        "ia_escopo_todas": "Todos los partidos",
        "ia_escopo_5": "Últimos 5 partidos",
        "ia_escopo_10": "Últimos 10 partidos",
        "ia_analisar": "🪄 Generar Informe de Rendimiento",
        "ia_gerando": "Analizando datos tácticos...",
        "ia_veredito": "📋 Veredicto del Asistente",
        "ia_partidas_usadas": "📌 Análisis basado en **{n}** partido(s)",
        "ia_erro": "❌ Error al generar el análisis. Inténtalo de nuevo.",
        "gols_vs_xg": "Goles vs xG a lo largo del tiempo",
        "login_aviso": "🔒 Inicia sesión para acceder",
        "btn_ir_login": "🔑 Ir al Login",
        "erro_usuario": "Error al cargar el usuario",
        "resultado_info": "{emoji} Resultado: **{resultado}** ({gols_u} x {gols_a})",
        "footer_email": "📧 E-Mail de contacto: onzevirtual1895@gmail.com",
        "footer_seguro": "🔒 Tus datos están seguros",
        "footer_canal": "Canal Onze Virtual FC",
        "footer_versao": "V 1.12",
        "lbl_idioma": "🌐 Idioma",
        # --- Importación HTML BepInEx ---
        "importar_titulo": "⚽ Importar Estadísticas de Jugadores",
        "importar_descricao": "Sube el HTML exportado por el mod BepInEx tras el partido para rellenar automáticamente las estadísticas individuales.",
        "importar_selecionar_partida": "Selecciona el partido para vincular las estadísticas",
        "importar_upload_label": "📂 Cargar archivo HTML de BepInEx",
        "importar_preview_titulo": "👁️ Vista previa — {n} jugador(es) encontrado(s)",
        "importar_confirmar": "✅ Confirmar y Guardar Estadísticas",
        "importar_sucesso": "✅ ¡Estadísticas de {n} jugadores importadas con éxito!",
        "importar_erro_parse": "❌ Error al leer el HTML. Asegúrate de que el archivo es un export válido de BepInEx.",
        "importar_erro_salvar": "❌ Error al guardar en la base de datos. Inténtalo de nuevo.",
        "importar_sem_jogadores": "⚠️ No se encontraron jugadores con minutos jugados en el archivo.",
        "importar_sem_partidas": "⚠️ No hay partidos registrados. Añade un partido antes de importar.",
        "importar_tab_principal": "📊 Principal",
        "importar_tab_passe": "🎯 Pase",
        "importar_tab_ofensivo": "⚔️ Ofensivo",
        "importar_tab_defensivo": "🛡️ Defensivo",
        "importar_tab_gr": "🧤 Portero",
        "importar_tab_bolas_paradas": "⚽ Balones Parados",
        "importar_reimportar_aviso": "⚠️ Este partido ya tiene estadísticas importadas. Confirmar reemplazará los datos anteriores.",
        "ver_stats_jogadores": "👥 Ver Estadísticas de Jugadores",
        "sem_stats_jogadores": "No hay estadísticas de jugadores importadas para este partido.",
    },
    "pt-pt": {
        "header_titulo": "⚽ FM Analytics 26",
        "header_caption": "Análise profissional para Football Manager",
        "tab_cadastro": "📝 Registar Partida",
        "tab_dashboard": "📊 Painel",
        "tab_historico": "📋 Histórico",
        "tab_ia": "🧠 Assistente IA",
        "cadastro_titulo": "📝 Registo da Partida",
        "lbl_seu_time": "A tua equipa",
        "lbl_adversario": "Adversário",
        "lbl_local": "Local do jogo",
        "lbl_resultado": "Resultado",
        "lbl_temporada": "Época (ex: 2025/26)",
        "lbl_rodada": "Jornada",
        "lbl_competicao": "Competição",
        "lbl_data": "Data da partida",
        "lbl_gols": "Golos",
        "lbl_posse": "Posse de bola (%)",
        "lbl_remates": "Remates",
        "lbl_remates_baliza": "Remates à baliza",
        "lbl_xg": "xG",
        "lbl_oportunidades": "Oportunidades flagrantes",
        "lbl_cantos": "Cantos",
        "lbl_passes_totais": "Passes totais",
        "lbl_passes_certos": "Passes certos",
        "lbl_cruzamentos_totais": "Cruzamentos totais",
        "lbl_cruzamentos_certos": "Cruzamentos certos",
        "lbl_seu_time_stats": "📊 A tua equipa",
        "lbl_adv_stats": "📉 Adversário",
        "btn_salvar": "💾 Guardar partida",
        "msg_sucesso": "✅ Partida guardada com sucesso!",
        "msg_salvando": "A guardar partida...",
        "limite_dica": "💡 Dica: Liberta espaço apagando partidas antigas",
        "limite_info": "Tens **{atual}/{max}** partidas registadas. Apaga algumas no separador '📋 Histórico' para libertar espaço.",
        "dashboard_titulo": "📊 Painel Geral",
        "filtros_titulo": "🔍 Filtros",
        "lbl_filtro_temporada": "Época",
        "lbl_filtro_competicao": "Competição",
        "filtro_todas": "Todas",
        "nenhuma_partida": "🎯 Nenhuma partida registada. Começa por adicionar a tua primeira partida!",
        "nenhum_filtro": "⚠️ Nenhuma partida encontrada com os filtros selecionados.",
        "resultados_titulo": "🏆 Resultados",
        "total_partidas": "🎯 Partidas",
        "vitorias": "✅ Vitórias",
        "empates": "🤝 Empates",
        "derrotas": "❌ Derrotas",
        "metrica_aproveitamento": "📊 Aproveitamento Geral",
        "dist_resultados": "Distribuição de Resultados",
        "casa_fora_titulo": "🏠 Desempenho: Casa x Fora",
        "em_casa": "🏠 Em Casa",
        "fora": "✈️ Fora",
        "aproveitamento": "Aproveitamento",
        "medias_titulo": "⚡ Médias",
        "gols_jogo": "Golos/jogo",
        "xg_jogo": "xG/jogo",
        "remates_jogo": "Remates/jogo",
        "remates_alvo_jogo": "Remates à baliza/jogo",
        "opor_flagrantes_jogo": "Oportunidades flagrantes/jogo",
        "posse_media": "Posse média",
        "acerto_passes": "Acerto de passes",
        "remates_alvo_perc": "Remates à baliza",
        "padrao_europeu": "🌍 Comparação com Padrão Europeu",
        "xg_por_jogo": "xG por jogo",
        "gols_por_jogo": "Golos por jogo",
        "remates_por_jogo": "Remates por jogo",
        "remates_alvo_label": "Remates à baliza",
        "posse_media_label": "Posse média (%)",
        "passes_certos_label": "Passes certos",
        "aproveitamento_label": "Aproveitamento (%)",
        "referencia": "Referência",
        "ultimos_5": "🔥 Últimos 5 Jogos (A tua equipa x Adversários)",
        "ultimos_5_casa_fora": "🔥 Últimos 5 Jogos (Casa x Fora)",
        "ultimos_5_casa": "🏠 Últimos 5 em Casa",
        "ultimos_5_fora": "✈️ Últimos 5 Fora",
        "nenhum_jogo_casa": "Nenhum jogo em casa.",
        "nenhum_jogo_fora": "Nenhum jogo fora.",
        "xg_medio": "xG médio",
        "cruzamentos_totais_jogo": "Cruzamentos totais/jogo",
        "cruzamentos_certos_jogo": "Cruzamentos certos/jogo",
        "cantos_jogo": "Cantos/jogo",
        "aprov_passes": "Aproveitamento de passes",
        "ultimos_5_casa_label": "Últimos 5 Casa",
        "ultimos_5_fora_label": "Últimos 5 Fora",
        "grafico_resultados": "Gráfico de Resultados",
        "resultados_casa_fora": "Resultados: Casa vs Fora",
        "historico_titulo": "📋 Histórico Completo de Partidas",
        "nenhuma_partida_hist": "Nenhuma partida registada.",
        "gerenciar_titulo": "🗑️ Gerir Partidas",
        "selecionar_deletar": "Seleciona uma partida para apagar",
        "btn_deletar": "🗑️ Apagar partida selecionada",
        "deletar_sucesso": "✅ Partida apagada com sucesso!",
        "deletar_erro": "❌ Erro ao apagar a partida.",
        "ia_titulo": "🧠 Assistente IA — Analista de Desempenho",
        "ia_descricao": "Análise tática baseada nos dados das tuas partidas registadas.",
        "ia_sem_partidas": "⚠️ Nenhuma partida registada. Adiciona partidas para ativar o Assistente IA.",
        "ia_minimo": "📊 Regista pelo menos **3 partidas** para uma análise mais fiável. Tens **{n}** partida(s).",
        "ia_selecionar": "🔍 Âmbito da análise",
        "ia_escopo_todas": "Todas as partidas",
        "ia_escopo_5": "Últimas 5 partidas",
        "ia_escopo_10": "Últimas 10 partidas",
        "ia_analisar": "🪄 Gerar Relatório de Desempenho",
        "ia_gerando": "A analisar dados táticos...",
        "ia_veredito": "📋 Veredito do Assistente",
        "ia_partidas_usadas": "📌 Análise baseada em **{n}** partida(s)",
        "ia_erro": "❌ Erro ao gerar análise. Tenta novamente.",
        "gols_vs_xg": "Golos vs xG ao longo do tempo",
        "login_aviso": "🔒 Faz login para aceder",
        "btn_ir_login": "🔑 Ir para Login",
        "erro_usuario": "Erro ao carregar utilizador",
        "resultado_info": "{emoji} Resultado: **{resultado}** ({gols_u} x {gols_a})",
        "footer_email": "📧 E-Mail para contacto: onzevirtual1895@gmail.com",
        "footer_seguro": "🔒 Os teus dados estão seguros",
        "footer_canal": "Canal Onze Virtual FC",
        "footer_versao": "V 1.12",
        "lbl_idioma": "🌐 Idioma",
        # --- Importação HTML BepInEx ---
        "importar_titulo": "⚽ Importar Estatísticas de Jogadores",
        "importar_descricao": "Carrega o HTML exportado pelo mod BepInEx após o jogo para preencher automaticamente as estatísticas individuais.",
        "importar_selecionar_partida": "Seleciona o jogo para associar as estatísticas",
        "importar_upload_label": "📂 Carregar ficheiro HTML do BepInEx",
        "importar_preview_titulo": "👁️ Pré-visualização — {n} jogador(es) encontrado(s)",
        "importar_confirmar": "✅ Confirmar e Guardar Estatísticas",
        "importar_sucesso": "✅ Estatísticas de {n} jogadores importadas com sucesso!",
        "importar_erro_parse": "❌ Erro ao ler o HTML. Certifica-te de que o ficheiro é um export válido do BepInEx.",
        "importar_erro_salvar": "❌ Erro ao guardar na base de dados. Tenta novamente.",
        "importar_sem_jogadores": "⚠️ Nenhum jogador com minutos jogados encontrado no ficheiro.",
        "importar_sem_partidas": "⚠️ Nenhum jogo registado. Regista um jogo antes de importar.",
        "importar_tab_principal": "📊 Principal",
        "importar_tab_passe": "🎯 Passe",
        "importar_tab_ofensivo": "⚔️ Ofensivo",
        "importar_tab_defensivo": "🛡️ Defensivo",
        "importar_tab_gr": "🧤 Guarda-Redes",
        "importar_tab_bolas_paradas": "⚽ Bolas Paradas",
        "importar_reimportar_aviso": "⚠️ Este jogo já tem estatísticas importadas. Confirmar substituirá os dados anteriores.",
        "ver_stats_jogadores": "👥 Ver Estatísticas dos Jogadores",
        "sem_stats_jogadores": "Nenhuma estatística de jogadores importada para este jogo.",
    },
}

IDIOMAS = {
    "🇧🇷 Português (BR)": "pt-br",
    "🇵🇹 Português (PT)": "pt-pt",
    "🇬🇧 English":        "en",
    "🇪🇸 Español":        "es",
}


def t(chave: str, lang: str = "pt-br") -> str:
    """Retorna o texto traduzido para o idioma informado. Fallback para pt-br."""
    return STRINGS.get(lang, STRINGS["pt-br"]).get(chave, STRINGS["pt-br"].get(chave, chave))
